### PR TITLE
updated description for deployment type

### PR DESCRIPTION
**Pull request by idealhack**
## Type of change

- documentation

## Description

A few existing PRs are not using the "deployment" type as intended, so it would be better to make it more explicit

## Related issues

No publicly available issues

### CODE REVIEW

**Review by bodhi — COMMENTED** [review]
Maybe I don't follow the original problem, but I'm not sure "(for another change)" makes it much clearer.

**Comment by idealhack** [comment]
As I think of what PRs we would have, there are a few types:

- bug
- feature
- documentation
- cleanup

These are fine in taxonomy. But sometimes you need _another_ PR to deploy them, e.g. it needs to happen in another repo. Now you could use `deployment` for it, or just use one or more of the above types if you are deploying multiple kinds of things. What I want to avoid is people using it with _only one_ change, since it does not add much information (all changes need to be deployed, but what kind of change are you deploying?)

Does it make sense?

**Comment by bodhi** [comment]
I think so, thanks!

**Comment by geckofu** [comment]
Sorry I still don't follow, can we have some examples?

**Comment by idealhack** [comment]
Sure. Since this is a public repo and I'm going to post some private repo links, I'm posting it in our Slack channel.

https://theplant.slack.com/archives/C06ATNP1892/p1706001253122319

**Comment by bodhi** [comment]
> Since this is a public repo

Does it need to be public?

**Comment by idealhack** [comment]
Unfortunately, as I tested, it has to be public to be a template for the org.

**Comment by idealhack** [comment]
Instead of opening a new PR, I'll just add another change here for a new type. @theplant/sre @bodhi could you please take a look again?

**Comment by idealhack** [comment]
@bodhi @theplant/sre Do you all have any other comments or concerns?

**Comment by bodhi** [comment]
@idealhack no I'm good, thanks.

**Pull request merged**
